# Generated by Django 6.0.7 on 2026-07-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='game_screenshots/'),
        ),
    ]
