# Generated by Django 6.0.7 on 2026-07-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_game_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='about',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshot',
            field=models.ImageField(upload_to='game_screenshots/'),
        ),
    ]
