# Generated by Django 6.0.7 on 2026-07-25 20:38

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_game_about_alter_game_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='screenshot',
            field=models.ImageField(upload_to=myapp.models.game_screenshot_path),
        ),
    ]
