# Generated by Django 6.0.7 on 2026-07-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_game_screenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='realise_date',
            field=models.DateField(),
        ),
    ]
