# Generated by Django 6.0.7 on 2026-07-26 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_game_options_game_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_company',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
